# Exported from Render on 2024-06-26T23:37:12Z
services:
- type: web
  name: Candela
  runtime: node
  repo: https://github.com/baxterj12/candelaNew
  plan: free
  envVars:
  - key: NODE_VERSION
    sync: false
  - key: SQUARE_LOCATION_ID
    sync: false
  - key: SQUARE_ACCESS_TOKEN
    sync: false
  - key: PORT
    sync: false
  region: ohio
  buildCommand: npm install; npm run build
  startCommand: npm run start
version: "1"
